#!/bin/zsh
set -euo pipefail
R="$HOME/Projects/devnotes"; F="$R/README.md"; mkdir -p "$R"; touch "$F"
# remove old block
grep -q "## Maintenance Overview (autogenerated)" "$F" && awk 'BEGIN{s=1}/## Maintenance Overview \(autogenerated\)/{s=0} s{print}' "$F" >"$F.tmp" && mv "$F.tmp" "$F"
# append fresh
{
  echo "## Maintenance Overview (autogenerated)"
  echo; echo "### Daily: Log Sentinel"; echo '```'; tail -n 10 "$R/backups/daily_rotate.log" 2>/dev/null || echo "(no log)"; echo '```'
  echo; echo "### Weekly: Downloads Tidy"; echo '```'; tail -n 10 "$HOME/Library/Application Support/Download_Archive/_tidy_weekly.log" 2>/dev/null || echo "(no log)"; echo '```'
  echo; echo "### Quick checks"; echo '```bash'; echo 'launchctl list | egrep \"logsentinel.daily|downloads.tidy.weekly|archive.compactor.monthly|maintenance.overview.daily\"'; echo '```'
} >>"$F"
