name: Build & Publish aiwatcher image
on:
  push:
    branches: [ "main" ]
    paths:
      - "docker/**"
      - "tools/alerts/**"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aiwatcher-live:latest
            ghcr.io/${{ github.repository_owner }}/aiwatcher-live:${{ github.sha }}
