name: Build & Publish aiwatcher image
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set lowercase owner
        id: lc
        run: echo "owner_lc=$(echo ${GITHUB_REPOSITORY_OWNER,,})" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.lc.outputs.owner_lc }}/aiwatcher-live:latest
